version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 1.10.0
    - 1.10.1
    - 1.9.0
    - 2.0.0
    - 2.0.1
    - 2.1.0
    - 2.2.0
    - 2.3.0
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: mermaid
    versions:
    - 8.9.0
    - 8.9.1
    - 8.9.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
    - 2.16.1
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: gatsby-plugin-layout
    versions:
    - 1.9.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
